#!/usr/bin/env bash 
# Normalized script pattern: https://github.blog/2015-06-30-scripts-to-rule-them-all/ ( https://github.com/github/scripts-to-rule-them-all )
# server is used to start the application.

echo "==========================="
echo "Running: script/server $@"
echo "==========================="
echo " "
echo " "


# DIR points to the ./script directory. ROOT point to the repository root
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT=$(cd $(dirname $DIR) && pwd)

# Set up environment variables, if _env exists
[ -f $DIR/_env ] && source $DIR/_env || echo "INFO: no environment .. continuing" 

# ============================================
# Add server code below
#



[ ! -d .external-config/ssh ] && mkdir -p .external-config/ssh
[ ! -d .external-config/env ] && mkdir -p .external-config/env

[ $# -eq 0 ] && CMD=start || CMD=$1

case $CMD in
	start)
		echo "Call script/setup"
		$ROOT/script/setup
		[ $? -gt 0 ] && exit 1
		vagrant up
		vagrant reload
		;;
	stop)
		vagrant halt
		;;
	destroy)
		vagrant destroy -f && echo "Server destroyed"
		;;
	reset)
		$DIR/server destroy
		$DIR/server start
		;;
esac

#
# END add server code
# ============================================

echo "==========================="
echo "done: script/server $@"
echo "==========================="
