#!/usr/bin/env bash 
# Normalized script pattern: https://github.blog/2015-06-30-scripts-to-rule-them-all/ ( https://github.com/github/scripts-to-rule-them-all )
# update is used to update the project after a fresh pull.

echo "==========================="
echo "Running: script/update"
echo "==========================="
echo " "
echo " "


# DIR points to the ./script directory. ROOT point to the repository root
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT=$(cd $(dirname $DIR) && pwd)

# Set up environment variables, if _env exists
[ -f $DIR/_env ] && source $DIR/_env || echo "INFO: no environment .. continuing" 

 
# ============================================
# Add server code below
#

echo "Call script/setup"
$ROOT/script/setup
[ $? -gt 0 ] && exit 1
cd $ROOT

vagrant ssh -c "sudo /vagrant/provision.sh"

#
# END add server code
# ============================================
 
echo "==========================="
echo "done: script/update"
echo "==========================="
